//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empl_Prob
    {
        public int id_employee { get; set; }
        public int id_problems { get; set; }
        public int id { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Problems Problems { get; set; }
    }
}
