//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PsihiEntities : DbContext
    {
        public PsihiEntities()
            : base("name=PsihiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Client_Employee> Client_Employee { get; set; }
        public virtual DbSet<Emp_Type> Emp_Type { get; set; }
        public virtual DbSet<Empl_Prob> Empl_Prob { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Position> Position { get; set; }
        public virtual DbSet<Problems> Problems { get; set; }
        public virtual DbSet<TypeTerapy> TypeTerapy { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
